[maranode_cef]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TIME_PREFIX = rt=
TIME_FORMAT = %s%3N
MAX_TIMESTAMP_LOOKAHEAD = 20
KV_MODE = none
REPORT-cef_fields = maranode_cef_extract

[source::...maranode*.cef]
sourcetype = maranode_cef
