[maranode_cef_extract]
REGEX = CEF:0\|[^\|]+\|[^\|]+\|[^\|]+\|(?P<sig_id>[^\|]+)\|(?P<event_name>[^\|]+)\|(?P<severity>[^\|]+)\|(?P<extensions>.+)
FORMAT = sig_id::$1 event_name::$2 severity::$3 extensions::$4

[maranode_kv_ext]
SOURCE_KEY = extensions
REGEX = (\w+)=([^\s]+)
FORMAT = $1::$2
MV_ADD = true
